/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.ioWRAP {

using System;
using System.Runtime.InteropServices;

public class h264HdrEventParsing : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal h264HdrEventParsing(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(h264HdrEventParsing obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~h264HdrEventParsing() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ioWRAPPINVOKE.delete_h264HdrEventParsing(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public h264HdrEventParsing() : this(ioWRAPPINVOKE.new_h264HdrEventParsing(), true) {
    SwigDirectorConnect();
  }

  public virtual int OnBeginHdr(h264HdrType_t eType, string pFuncName) {
    int ret = (SwigDerivedClassHasMethod("OnBeginHdr", swigMethodTypes0) ? ioWRAPPINVOKE.h264HdrEventParsing_OnBeginHdrSwigExplicith264HdrEventParsing__SWIG_0(swigCPtr, (int)eType, pFuncName) : ioWRAPPINVOKE.h264HdrEventParsing_OnBeginHdr__SWIG_0(swigCPtr, (int)eType, pFuncName));
    return ret;
  }

  public virtual int OnBeginHdr(h264HdrType_t eType) {
    int ret = (SwigDerivedClassHasMethod("OnBeginHdr", swigMethodTypes1) ? ioWRAPPINVOKE.h264HdrEventParsing_OnBeginHdrSwigExplicith264HdrEventParsing__SWIG_1(swigCPtr, (int)eType) : ioWRAPPINVOKE.h264HdrEventParsing_OnBeginHdr__SWIG_1(swigCPtr, (int)eType));
    return ret;
  }

  public virtual int OnEndHdr(h264HdrType_t eType) {
    int ret = (SwigDerivedClassHasMethod("OnEndHdr", swigMethodTypes2) ? ioWRAPPINVOKE.h264HdrEventParsing_OnEndHdrSwigExplicith264HdrEventParsing(swigCPtr, (int)eType) : ioWRAPPINVOKE.h264HdrEventParsing_OnEndHdr(swigCPtr, (int)eType));
    return ret;
  }

  public virtual int OnErrorHdr(h264HdrType_t eType) {
    int ret = (SwigDerivedClassHasMethod("OnErrorHdr", swigMethodTypes3) ? ioWRAPPINVOKE.h264HdrEventParsing_OnErrorHdrSwigExplicith264HdrEventParsing(swigCPtr, (int)eType) : ioWRAPPINVOKE.h264HdrEventParsing_OnErrorHdr(swigCPtr, (int)eType));
    return ret;
  }

  public virtual int OnBeginFunc(string pFuncName) {
    int ret = (SwigDerivedClassHasMethod("OnBeginFunc", swigMethodTypes4) ? ioWRAPPINVOKE.h264HdrEventParsing_OnBeginFuncSwigExplicith264HdrEventParsing(swigCPtr, pFuncName) : ioWRAPPINVOKE.h264HdrEventParsing_OnBeginFunc(swigCPtr, pFuncName));
    return ret;
  }

  public virtual int OnEndFunc(string pFuncName) {
    int ret = (SwigDerivedClassHasMethod("OnEndFunc", swigMethodTypes5) ? ioWRAPPINVOKE.h264HdrEventParsing_OnEndFuncSwigExplicith264HdrEventParsing(swigCPtr, pFuncName) : ioWRAPPINVOKE.h264HdrEventParsing_OnEndFunc(swigCPtr, pFuncName));
    return ret;
  }

  public virtual int OnSyntaxElt(string pName, string pDescriptor, int value) {
    int ret = (SwigDerivedClassHasMethod("OnSyntaxElt", swigMethodTypes6) ? ioWRAPPINVOKE.h264HdrEventParsing_OnSyntaxEltSwigExplicith264HdrEventParsing(swigCPtr, pName, pDescriptor, value) : ioWRAPPINVOKE.h264HdrEventParsing_OnSyntaxElt(swigCPtr, pName, pDescriptor, value));
    return ret;
  }

  public virtual int OnBeginCtrl(string pName, string pExpression, int value) {
    int ret = (SwigDerivedClassHasMethod("OnBeginCtrl", swigMethodTypes7) ? ioWRAPPINVOKE.h264HdrEventParsing_OnBeginCtrlSwigExplicith264HdrEventParsing(swigCPtr, pName, pExpression, value) : ioWRAPPINVOKE.h264HdrEventParsing_OnBeginCtrl(swigCPtr, pName, pExpression, value));
    return ret;
  }

  public virtual int OnEndCtrl(string pName) {
    int ret = (SwigDerivedClassHasMethod("OnEndCtrl", swigMethodTypes8) ? ioWRAPPINVOKE.h264HdrEventParsing_OnEndCtrlSwigExplicith264HdrEventParsing(swigCPtr, pName) : ioWRAPPINVOKE.h264HdrEventParsing_OnEndCtrl(swigCPtr, pName));
    return ret;
  }

  public virtual int OnFrameDraw(IntPtr pLum, IntPtr pCb, IntPtr pCr, uint uiWidth, uint uiHeight, uint uiStride) {
    int ret = (SwigDerivedClassHasMethod("OnFrameDraw", swigMethodTypes9) ? ioWRAPPINVOKE.h264HdrEventParsing_OnFrameDrawSwigExplicith264HdrEventParsing(swigCPtr, pLum, pCb, pCr, uiWidth, uiHeight, uiStride) : ioWRAPPINVOKE.h264HdrEventParsing_OnFrameDraw(swigCPtr, pLum, pCb, pCr, uiWidth, uiHeight, uiStride));
    return ret;
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("OnBeginHdr", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateh264HdrEventParsing_0(SwigDirectorOnBeginHdr__SWIG_0);
    if (SwigDerivedClassHasMethod("OnBeginHdr", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateh264HdrEventParsing_1(SwigDirectorOnBeginHdr__SWIG_1);
    if (SwigDerivedClassHasMethod("OnEndHdr", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateh264HdrEventParsing_2(SwigDirectorOnEndHdr);
    if (SwigDerivedClassHasMethod("OnErrorHdr", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateh264HdrEventParsing_3(SwigDirectorOnErrorHdr);
    if (SwigDerivedClassHasMethod("OnBeginFunc", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateh264HdrEventParsing_4(SwigDirectorOnBeginFunc);
    if (SwigDerivedClassHasMethod("OnEndFunc", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateh264HdrEventParsing_5(SwigDirectorOnEndFunc);
    if (SwigDerivedClassHasMethod("OnSyntaxElt", swigMethodTypes6))
      swigDelegate6 = new SwigDelegateh264HdrEventParsing_6(SwigDirectorOnSyntaxElt);
    if (SwigDerivedClassHasMethod("OnBeginCtrl", swigMethodTypes7))
      swigDelegate7 = new SwigDelegateh264HdrEventParsing_7(SwigDirectorOnBeginCtrl);
    if (SwigDerivedClassHasMethod("OnEndCtrl", swigMethodTypes8))
      swigDelegate8 = new SwigDelegateh264HdrEventParsing_8(SwigDirectorOnEndCtrl);
    if (SwigDerivedClassHasMethod("OnFrameDraw", swigMethodTypes9))
      swigDelegate9 = new SwigDelegateh264HdrEventParsing_9(SwigDirectorOnFrameDraw);
    ioWRAPPINVOKE.h264HdrEventParsing_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6, swigDelegate7, swigDelegate8, swigDelegate9);
  }

  private bool SwigDerivedClassHasMethod(string methodName, Type[] methodTypes) {
    System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(h264HdrEventParsing));
    return hasDerivedMethod;
  }

  private int SwigDirectorOnBeginHdr__SWIG_0(int eType, string pFuncName) {
    return OnBeginHdr((h264HdrType_t)eType, pFuncName);
  }

  private int SwigDirectorOnBeginHdr__SWIG_1(int eType) {
    return OnBeginHdr((h264HdrType_t)eType);
  }

  private int SwigDirectorOnEndHdr(int eType) {
    return OnEndHdr((h264HdrType_t)eType);
  }

  private int SwigDirectorOnErrorHdr(int eType) {
    return OnErrorHdr((h264HdrType_t)eType);
  }

  private int SwigDirectorOnBeginFunc(string pFuncName) {
    return OnBeginFunc(pFuncName);
  }

  private int SwigDirectorOnEndFunc(string pFuncName) {
    return OnEndFunc(pFuncName);
  }

  private int SwigDirectorOnSyntaxElt(string pName, string pDescriptor, int value) {
    return OnSyntaxElt(pName, pDescriptor, value);
  }

  private int SwigDirectorOnBeginCtrl(string pName, string pExpression, int value) {
    return OnBeginCtrl(pName, pExpression, value);
  }

  private int SwigDirectorOnEndCtrl(string pName) {
    return OnEndCtrl(pName);
  }

  private int SwigDirectorOnFrameDraw(IntPtr pLum, IntPtr pCb, IntPtr pCr, uint uiWidth, uint uiHeight, uint uiStride) {
    return OnFrameDraw(pLum, pCb, pCr, uiWidth, uiHeight, uiStride);
  }

  public delegate int SwigDelegateh264HdrEventParsing_0(int eType, string pFuncName);
  public delegate int SwigDelegateh264HdrEventParsing_1(int eType);
  public delegate int SwigDelegateh264HdrEventParsing_2(int eType);
  public delegate int SwigDelegateh264HdrEventParsing_3(int eType);
  public delegate int SwigDelegateh264HdrEventParsing_4(string pFuncName);
  public delegate int SwigDelegateh264HdrEventParsing_5(string pFuncName);
  public delegate int SwigDelegateh264HdrEventParsing_6(string pName, string pDescriptor, int value);
  public delegate int SwigDelegateh264HdrEventParsing_7(string pName, string pExpression, int value);
  public delegate int SwigDelegateh264HdrEventParsing_8(string pName);
  public delegate int SwigDelegateh264HdrEventParsing_9(IntPtr pLum, IntPtr pCb, IntPtr pCr, uint uiWidth, uint uiHeight, uint uiStride);

  private SwigDelegateh264HdrEventParsing_0 swigDelegate0;
  private SwigDelegateh264HdrEventParsing_1 swigDelegate1;
  private SwigDelegateh264HdrEventParsing_2 swigDelegate2;
  private SwigDelegateh264HdrEventParsing_3 swigDelegate3;
  private SwigDelegateh264HdrEventParsing_4 swigDelegate4;
  private SwigDelegateh264HdrEventParsing_5 swigDelegate5;
  private SwigDelegateh264HdrEventParsing_6 swigDelegate6;
  private SwigDelegateh264HdrEventParsing_7 swigDelegate7;
  private SwigDelegateh264HdrEventParsing_8 swigDelegate8;
  private SwigDelegateh264HdrEventParsing_9 swigDelegate9;

  private static Type[] swigMethodTypes0 = new Type[] { typeof(h264HdrType_t), typeof(string) };
  private static Type[] swigMethodTypes1 = new Type[] { typeof(h264HdrType_t) };
  private static Type[] swigMethodTypes2 = new Type[] { typeof(h264HdrType_t) };
  private static Type[] swigMethodTypes3 = new Type[] { typeof(h264HdrType_t) };
  private static Type[] swigMethodTypes4 = new Type[] { typeof(string) };
  private static Type[] swigMethodTypes5 = new Type[] { typeof(string) };
  private static Type[] swigMethodTypes6 = new Type[] { typeof(string), typeof(string), typeof(int) };
  private static Type[] swigMethodTypes7 = new Type[] { typeof(string), typeof(string), typeof(int) };
  private static Type[] swigMethodTypes8 = new Type[] { typeof(string) };
  private static Type[] swigMethodTypes9 = new Type[] { typeof(IntPtr), typeof(IntPtr), typeof(IntPtr), typeof(uint), typeof(uint), typeof(uint) };
}

}
