/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_ioWRAP_WRAP_H_
#define SWIG_ioWRAP_WRAP_H_

class SwigDirector_h264HdrEventParsing : public h264HdrEventParsing, public Swig::Director {

public:
    SwigDirector_h264HdrEventParsing();
    virtual ~SwigDirector_h264HdrEventParsing();
    virtual int OnBeginHdr(h264HdrType_t eType, char const *pFuncName = NULL) const;
    virtual int OnEndHdr(h264HdrType_t eType) const;
    virtual int OnErrorHdr(h264HdrType_t eType) const;
    virtual int OnBeginFunc(char const *pFuncName) const;
    virtual int OnEndFunc(char const *pFuncName) const;
    virtual int OnSyntaxElt(char const *pName, char const *pDescriptor, int value) const;
    virtual int OnBeginCtrl(char const *pName, char const *pExpression, int value) const;
    virtual int OnEndCtrl(char const *pName) const;
    virtual int OnFrameDraw(void const *pLum, void const *pCb, void const *pCr, unsigned int uiWidth, unsigned int uiHeight, unsigned int uiStride) const;

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)(int, char *);
    typedef int (SWIGSTDCALL* SWIG_Callback1_t)(int);
    typedef int (SWIGSTDCALL* SWIG_Callback2_t)(int);
    typedef int (SWIGSTDCALL* SWIG_Callback3_t)(int);
    typedef int (SWIGSTDCALL* SWIG_Callback4_t)(char *);
    typedef int (SWIGSTDCALL* SWIG_Callback5_t)(char *);
    typedef int (SWIGSTDCALL* SWIG_Callback6_t)(char *, char *, int);
    typedef int (SWIGSTDCALL* SWIG_Callback7_t)(char *, char *, int);
    typedef int (SWIGSTDCALL* SWIG_Callback8_t)(char *);
    typedef int (SWIGSTDCALL* SWIG_Callback9_t)(void *, void *, void *, unsigned int, unsigned int, unsigned int);
    void swig_connect_director(SWIG_Callback0_t callbackOnBeginHdr__SWIG_0, SWIG_Callback1_t callbackOnBeginHdr__SWIG_1, SWIG_Callback2_t callbackOnEndHdr, SWIG_Callback3_t callbackOnErrorHdr, SWIG_Callback4_t callbackOnBeginFunc, SWIG_Callback5_t callbackOnEndFunc, SWIG_Callback6_t callbackOnSyntaxElt, SWIG_Callback7_t callbackOnBeginCtrl, SWIG_Callback8_t callbackOnEndCtrl, SWIG_Callback9_t callbackOnFrameDraw);

private:
    SWIG_Callback0_t swig_callbackOnBeginHdr__SWIG_0;
    SWIG_Callback1_t swig_callbackOnBeginHdr__SWIG_1;
    SWIG_Callback2_t swig_callbackOnEndHdr;
    SWIG_Callback3_t swig_callbackOnErrorHdr;
    SWIG_Callback4_t swig_callbackOnBeginFunc;
    SWIG_Callback5_t swig_callbackOnEndFunc;
    SWIG_Callback6_t swig_callbackOnSyntaxElt;
    SWIG_Callback7_t swig_callbackOnBeginCtrl;
    SWIG_Callback8_t swig_callbackOnEndCtrl;
    SWIG_Callback9_t swig_callbackOnFrameDraw;
    void swig_init_callbacks();
};


#endif
