/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.ioWRAP {

using System;
using System.Runtime.InteropServices;

public class Md5 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Md5(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Md5 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Md5() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ioWRAPPINVOKE.delete_Md5(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Md5() : this(ioWRAPPINVOKE.new_Md5(), true) {
  }

  public void init() {
    ioWRAPPINVOKE.Md5_init(swigCPtr);
  }

  public void update(IntPtr p_ptr, uint u_size) {
    ioWRAPPINVOKE.Md5_update(swigCPtr, p_ptr, u_size);
  }

  public string final() {
    string ret = ioWRAPPINVOKE.Md5_final(swigCPtr);
    return ret;
  }

  public string compute(IntPtr p_ptr, uint u_size) {
    string ret = ioWRAPPINVOKE.Md5_compute(swigCPtr, p_ptr, u_size);
    return ret;
  }

}

}
