/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.ioWRAP {

using System;
using System.Runtime.InteropServices;

public class VideoConverterYUV420ToRGB32 : VideoConverter {
  private HandleRef swigCPtr;

  internal VideoConverterYUV420ToRGB32(IntPtr cPtr, bool cMemoryOwn) : base(ioWRAPPINVOKE.VideoConverterYUV420ToRGB32_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(VideoConverterYUV420ToRGB32 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~VideoConverterYUV420ToRGB32() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ioWRAPPINVOKE.delete_VideoConverterYUV420ToRGB32(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public VideoConverterYUV420ToRGB32() : this(ioWRAPPINVOKE.new_VideoConverterYUV420ToRGB32(), true) {
  }

  public static bool convert(IntPtr pLum, IntPtr pCb, IntPtr pCr, uint uiWidth, uint uiHeight, uint uiStride, IntPtr pOutput, uint nOutputSize) {
    bool ret = ioWRAPPINVOKE.VideoConverterYUV420ToRGB32_convert(pLum, pCb, pCr, uiWidth, uiHeight, uiStride, pOutput, nOutputSize);
    return ret;
  }

}

}
