/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

public enum BlkMode {
  BLK_8x8 = 8,
  BLK_8x4 = 9,
  BLK_4x8 = 10,
  BLK_4x4 = 11,
  BLK_SKIP = 0
}

}
