/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

using System;
using System.Runtime.InteropServices;

public class CommonEltVector : IDisposable, System.Collections.IEnumerable
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerable<CommonElt>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CommonEltVector(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CommonEltVector obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CommonEltVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          commonWRAPPINVOKE.delete_CommonEltVector(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public CommonEltVector(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (CommonElt element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public CommonElt this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array)
#else
  public void CopyTo(CommonElt[] array)
#endif
  {
    CopyTo(0, array, 0, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array, int arrayIndex)
#else
  public void CopyTo(CommonElt[] array, int arrayIndex)
#endif
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(int index, System.Array array, int arrayIndex, int count)
#else
  public void CopyTo(int index, CommonElt[] array, int arrayIndex, int count)
#endif
  {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

#if !SWIG_DOTNET_1
  System.Collections.Generic.IEnumerator<CommonElt> System.Collections.Generic.IEnumerable<CommonElt>.GetEnumerator() {
    return new CommonEltVectorEnumerator(this);
  }
#endif

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new CommonEltVectorEnumerator(this);
  }

  public CommonEltVectorEnumerator GetEnumerator() {
    return new CommonEltVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class CommonEltVectorEnumerator : System.Collections.IEnumerator
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerator<CommonElt>
#endif
  {
    private CommonEltVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public CommonEltVectorEnumerator(CommonEltVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public CommonElt Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (CommonElt)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

#if !SWIG_DOTNET_1
    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
#endif
  }

  public void Clear() {
    commonWRAPPINVOKE.CommonEltVector_Clear(swigCPtr);
  }

  public void Add(CommonElt x) {
    commonWRAPPINVOKE.CommonEltVector_Add(swigCPtr, CommonElt.getCPtr(x));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = commonWRAPPINVOKE.CommonEltVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = commonWRAPPINVOKE.CommonEltVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    commonWRAPPINVOKE.CommonEltVector_reserve(swigCPtr, n);
  }

  public CommonEltVector() : this(commonWRAPPINVOKE.new_CommonEltVector__SWIG_0(), true) {
  }

  public CommonEltVector(CommonEltVector other) : this(commonWRAPPINVOKE.new_CommonEltVector__SWIG_1(CommonEltVector.getCPtr(other)), true) {
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public CommonEltVector(int capacity) : this(commonWRAPPINVOKE.new_CommonEltVector__SWIG_2(capacity), true) {
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  private CommonElt getitemcopy(int index) {
    CommonElt ret = new CommonElt(commonWRAPPINVOKE.CommonEltVector_getitemcopy(swigCPtr, index), true);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private CommonElt getitem(int index) {
    CommonElt ret = new CommonElt(commonWRAPPINVOKE.CommonEltVector_getitem(swigCPtr, index), false);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, CommonElt val) {
    commonWRAPPINVOKE.CommonEltVector_setitem(swigCPtr, index, CommonElt.getCPtr(val));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(CommonEltVector values) {
    commonWRAPPINVOKE.CommonEltVector_AddRange(swigCPtr, CommonEltVector.getCPtr(values));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public CommonEltVector GetRange(int index, int count) {
    IntPtr cPtr = commonWRAPPINVOKE.CommonEltVector_GetRange(swigCPtr, index, count);
    CommonEltVector ret = (cPtr == IntPtr.Zero) ? null : new CommonEltVector(cPtr, true);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, CommonElt x) {
    commonWRAPPINVOKE.CommonEltVector_Insert(swigCPtr, index, CommonElt.getCPtr(x));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, CommonEltVector values) {
    commonWRAPPINVOKE.CommonEltVector_InsertRange(swigCPtr, index, CommonEltVector.getCPtr(values));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    commonWRAPPINVOKE.CommonEltVector_RemoveAt(swigCPtr, index);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    commonWRAPPINVOKE.CommonEltVector_RemoveRange(swigCPtr, index, count);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public static CommonEltVector Repeat(CommonElt value, int count) {
    IntPtr cPtr = commonWRAPPINVOKE.CommonEltVector_Repeat(CommonElt.getCPtr(value), count);
    CommonEltVector ret = (cPtr == IntPtr.Zero) ? null : new CommonEltVector(cPtr, true);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    commonWRAPPINVOKE.CommonEltVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    commonWRAPPINVOKE.CommonEltVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, CommonEltVector values) {
    commonWRAPPINVOKE.CommonEltVector_SetRange(swigCPtr, index, CommonEltVector.getCPtr(values));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
