/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

public enum CommonEltMbDataType_t {
  CommonEltMbDataType_Final,
  CommonEltMbDataType_PreFilter,
  CommonEltMbDataType_Predicted,
  CommonEltMbDataType_Residual,
  CommonEltMbDataType_ResidualBase,
  CommonEltMbDataType_IDCTCoeffsQuant,
  CommonEltMbDataType_IDCTCoeffsScale
}

}
