/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

using System;
using System.Runtime.InteropServices;

public class CommonSyntax : CommonElt {
  private HandleRef swigCPtr;

  internal CommonSyntax(IntPtr cPtr, bool cMemoryOwn) : base(commonWRAPPINVOKE.CommonSyntax_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CommonSyntax obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CommonSyntax() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          commonWRAPPINVOKE.delete_CommonSyntax(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public CommonSyntax(string strName, string strDescriptor, double dValue) : this(commonWRAPPINVOKE.new_CommonSyntax(strName, strDescriptor, dValue), true) {
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getName() {
    string ret = commonWRAPPINVOKE.CommonSyntax_getName(swigCPtr);
    return ret;
  }

  public string getDescriptor() {
    string ret = commonWRAPPINVOKE.CommonSyntax_getDescriptor(swigCPtr);
    return ret;
  }

  public double getValue() {
    double ret = commonWRAPPINVOKE.CommonSyntax_getValue(swigCPtr);
    return ret;
  }

}

}
