/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

using System;
using System.Runtime.InteropServices;

public class CommonMb : CommonElt {
  private HandleRef swigCPtr;

  internal CommonMb(IntPtr cPtr, bool cMemoryOwn) : base(commonWRAPPINVOKE.CommonMb_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CommonMb obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CommonMb() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          commonWRAPPINVOKE.delete_CommonMb(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public CommonMb(uint uiAddress, uint uiX, uint uiY, CommonEltMbType_t eMbType) : this(commonWRAPPINVOKE.new_CommonMb__SWIG_0(uiAddress, uiX, uiY, (int)eMbType), true) {
  }

  public CommonMb(uint uiAddress, uint uiX, uint uiY) : this(commonWRAPPINVOKE.new_CommonMb__SWIG_1(uiAddress, uiX, uiY), true) {
  }

  public virtual IntPtr getData(CommonEltMbDataType_t eType, CommonYuvLine_t eLine) { return commonWRAPPINVOKE.CommonMb_getData(swigCPtr, (int)eType, (int)eLine); }

  public CommonEltMbType_t getMbType() {
    CommonEltMbType_t ret = (CommonEltMbType_t)commonWRAPPINVOKE.CommonMb_getMbType(swigCPtr);
    return ret;
  }

  public uint getAddress() {
    uint ret = commonWRAPPINVOKE.CommonMb_getAddress(swigCPtr);
    return ret;
  }

  public uint getX() {
    uint ret = commonWRAPPINVOKE.CommonMb_getX(swigCPtr);
    return ret;
  }

  public uint getY() {
    uint ret = commonWRAPPINVOKE.CommonMb_getY(swigCPtr);
    return ret;
  }

  public uint getWidth(CommonYuvLine_t eLine) {
    uint ret = commonWRAPPINVOKE.CommonMb_getWidth(swigCPtr, (int)eLine);
    return ret;
  }

  public uint getHeight(CommonYuvLine_t eLine) {
    uint ret = commonWRAPPINVOKE.CommonMb_getHeight(swigCPtr, (int)eLine);
    return ret;
  }

}

}
