/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

using System;
using System.Runtime.InteropServices;

public class CommonHeader : CommonElt {
  private HandleRef swigCPtr;

  internal CommonHeader(IntPtr cPtr, bool cMemoryOwn) : base(commonWRAPPINVOKE.CommonHeader_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CommonHeader obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CommonHeader() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          commonWRAPPINVOKE.delete_CommonHeader(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public CommonHeader(CommonHeaderType_t eType, string strFuncName) : this(commonWRAPPINVOKE.new_CommonHeader((int)eType, strFuncName), true) {
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual CommonHeaderType_t getHeaderType() {
    CommonHeaderType_t ret = (CommonHeaderType_t)commonWRAPPINVOKE.CommonHeader_getHeaderType(swigCPtr);
    return ret;
  }

  public virtual string getFuncName() {
    string ret = commonWRAPPINVOKE.CommonHeader_getFuncName(swigCPtr);
    return ret;
  }

}

}
