/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

using System;
using System.Runtime.InteropServices;

public class CommonEltVectorPtr : IDisposable, System.Collections.IEnumerable
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IList<CommonElt>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CommonEltVectorPtr(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CommonEltVectorPtr obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CommonEltVectorPtr() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          commonWRAPPINVOKE.delete_CommonEltVectorPtr(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public CommonEltVectorPtr(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (CommonElt element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public CommonElt this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array)
#else
  public void CopyTo(CommonElt[] array)
#endif
  {
    CopyTo(0, array, 0, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array, int arrayIndex)
#else
  public void CopyTo(CommonElt[] array, int arrayIndex)
#endif
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(int index, System.Array array, int arrayIndex, int count)
#else
  public void CopyTo(int index, CommonElt[] array, int arrayIndex, int count)
#endif
  {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

#if !SWIG_DOTNET_1
  System.Collections.Generic.IEnumerator<CommonElt> System.Collections.Generic.IEnumerable<CommonElt>.GetEnumerator() {
    return new CommonEltVectorPtrEnumerator(this);
  }
#endif

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new CommonEltVectorPtrEnumerator(this);
  }

  public CommonEltVectorPtrEnumerator GetEnumerator() {
    return new CommonEltVectorPtrEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class CommonEltVectorPtrEnumerator : System.Collections.IEnumerator
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerator<CommonElt>
#endif
  {
    private CommonEltVectorPtr collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public CommonEltVectorPtrEnumerator(CommonEltVectorPtr collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public CommonElt Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (CommonElt)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

#if !SWIG_DOTNET_1
    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
#endif
  }

  public void Clear() {
    commonWRAPPINVOKE.CommonEltVectorPtr_Clear(swigCPtr);
  }

  public void Add(CommonElt x) {
    commonWRAPPINVOKE.CommonEltVectorPtr_Add(swigCPtr, CommonElt.getCPtr(x));
  }

  private uint size() {
    uint ret = commonWRAPPINVOKE.CommonEltVectorPtr_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = commonWRAPPINVOKE.CommonEltVectorPtr_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    commonWRAPPINVOKE.CommonEltVectorPtr_reserve(swigCPtr, n);
  }

  public CommonEltVectorPtr() : this(commonWRAPPINVOKE.new_CommonEltVectorPtr__SWIG_0(), true) {
  }

  public CommonEltVectorPtr(CommonEltVectorPtr other) : this(commonWRAPPINVOKE.new_CommonEltVectorPtr__SWIG_1(CommonEltVectorPtr.getCPtr(other)), true) {
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public CommonEltVectorPtr(int capacity) : this(commonWRAPPINVOKE.new_CommonEltVectorPtr__SWIG_2(capacity), true) {
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  private CommonElt getitemcopy(int index) {
    IntPtr cPtr = commonWRAPPINVOKE.CommonEltVectorPtr_getitemcopy(swigCPtr, index);
    CommonElt ret = (cPtr == IntPtr.Zero) ? null : new CommonElt(cPtr, false);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private CommonElt getitem(int index) {
    IntPtr cPtr = commonWRAPPINVOKE.CommonEltVectorPtr_getitem(swigCPtr, index);
    CommonElt ret = (cPtr == IntPtr.Zero) ? null : new CommonElt(cPtr, false);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, CommonElt val) {
    commonWRAPPINVOKE.CommonEltVectorPtr_setitem(swigCPtr, index, CommonElt.getCPtr(val));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(CommonEltVectorPtr values) {
    commonWRAPPINVOKE.CommonEltVectorPtr_AddRange(swigCPtr, CommonEltVectorPtr.getCPtr(values));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public CommonEltVectorPtr GetRange(int index, int count) {
    IntPtr cPtr = commonWRAPPINVOKE.CommonEltVectorPtr_GetRange(swigCPtr, index, count);
    CommonEltVectorPtr ret = (cPtr == IntPtr.Zero) ? null : new CommonEltVectorPtr(cPtr, true);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, CommonElt x) {
    commonWRAPPINVOKE.CommonEltVectorPtr_Insert(swigCPtr, index, CommonElt.getCPtr(x));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, CommonEltVectorPtr values) {
    commonWRAPPINVOKE.CommonEltVectorPtr_InsertRange(swigCPtr, index, CommonEltVectorPtr.getCPtr(values));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    commonWRAPPINVOKE.CommonEltVectorPtr_RemoveAt(swigCPtr, index);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    commonWRAPPINVOKE.CommonEltVectorPtr_RemoveRange(swigCPtr, index, count);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public static CommonEltVectorPtr Repeat(CommonElt value, int count) {
    IntPtr cPtr = commonWRAPPINVOKE.CommonEltVectorPtr_Repeat(CommonElt.getCPtr(value), count);
    CommonEltVectorPtr ret = (cPtr == IntPtr.Zero) ? null : new CommonEltVectorPtr(cPtr, true);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    commonWRAPPINVOKE.CommonEltVectorPtr_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    commonWRAPPINVOKE.CommonEltVectorPtr_Reverse__SWIG_1(swigCPtr, index, count);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, CommonEltVectorPtr values) {
    commonWRAPPINVOKE.CommonEltVectorPtr_SetRange(swigCPtr, index, CommonEltVectorPtr.getCPtr(values));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(CommonElt value) {
    bool ret = commonWRAPPINVOKE.CommonEltVectorPtr_Contains(swigCPtr, CommonElt.getCPtr(value));
    return ret;
  }

  public int IndexOf(CommonElt value) {
    int ret = commonWRAPPINVOKE.CommonEltVectorPtr_IndexOf(swigCPtr, CommonElt.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(CommonElt value) {
    int ret = commonWRAPPINVOKE.CommonEltVectorPtr_LastIndexOf(swigCPtr, CommonElt.getCPtr(value));
    return ret;
  }

  public bool Remove(CommonElt value) {
    bool ret = commonWRAPPINVOKE.CommonEltVectorPtr_Remove(swigCPtr, CommonElt.getCPtr(value));
    return ret;
  }

}

}
