/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

using System;
using System.Runtime.InteropServices;

public class commonWRAP {
  public static readonly int COMMON_MAX_TRACE_LAYERS = commonWRAPPINVOKE.COMMON_MAX_TRACE_LAYERS_get();
  public static readonly int COMMON_MAX_BITS_LENGTH = commonWRAPPINVOKE.COMMON_MAX_BITS_LENGTH_get();
  public static readonly int COMMON_MAX_LINE_LENGTH = commonWRAPPINVOKE.COMMON_MAX_LINE_LENGTH_get();
}

}
