/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

using System;
using System.Runtime.InteropServices;

public class CommonH264Nalu : CommonElt {
  private HandleRef swigCPtr;

  internal CommonH264Nalu(IntPtr cPtr, bool cMemoryOwn) : base(commonWRAPPINVOKE.CommonH264Nalu_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CommonH264Nalu obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CommonH264Nalu() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          commonWRAPPINVOKE.delete_CommonH264Nalu(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public NalUnitType getNaluType() {
    NalUnitType ret = (NalUnitType)commonWRAPPINVOKE.CommonH264Nalu_getNaluType(swigCPtr);
    return ret;
  }

  public uint getLayerId() {
    uint ret = commonWRAPPINVOKE.CommonH264Nalu_getLayerId(swigCPtr);
    return ret;
  }

  public uint getPictureId() {
    uint ret = commonWRAPPINVOKE.CommonH264Nalu_getPictureId(swigCPtr);
    return ret;
  }

  public uint getSliceId() {
    uint ret = commonWRAPPINVOKE.CommonH264Nalu_getSliceId(swigCPtr);
    return ret;
  }

}

}
