/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

using System;
using System.Runtime.InteropServices;

public class CommonMv : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CommonMv(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CommonMv obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CommonMv() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          commonWRAPPINVOKE.delete_CommonMv(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int x {
    set {
      commonWRAPPINVOKE.CommonMv_x_set(swigCPtr, value);
    } 
    get {
      int ret = commonWRAPPINVOKE.CommonMv_x_get(swigCPtr);
      return ret;
    } 
  }

  public int y {
    set {
      commonWRAPPINVOKE.CommonMv_y_set(swigCPtr, value);
    } 
    get {
      int ret = commonWRAPPINVOKE.CommonMv_y_get(swigCPtr);
      return ret;
    } 
  }

}

}
