/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

using System;
using System.Runtime.InteropServices;

public class CommonElt : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CommonElt(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CommonElt obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CommonElt() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          commonWRAPPINVOKE.delete_CommonElt(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual CommonElementType_t getType() {
    CommonElementType_t ret = (CommonElementType_t)commonWRAPPINVOKE.CommonElt_getType(swigCPtr);
    return ret;
  }

  public virtual CommonEltVectorPtr getElements() {
    CommonEltVectorPtr ret = new CommonEltVectorPtr(commonWRAPPINVOKE.CommonElt_getElements(swigCPtr), true);
    return ret;
  }

  public virtual string getBitsStart() {
    string ret = commonWRAPPINVOKE.CommonElt_getBitsStart(swigCPtr);
    return ret;
  }

  public virtual string getBitsVal() {
    string ret = commonWRAPPINVOKE.CommonElt_getBitsVal(swigCPtr);
    return ret;
  }

  public virtual uint getBitsCount() {
    uint ret = commonWRAPPINVOKE.CommonElt_getBitsCount(swigCPtr);
    return ret;
  }

}

}
