/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_commonWRAP_WRAP_H_
#define SWIG_commonWRAP_WRAP_H_

class SwigDirector_CommonMain : public CommonMain, public Swig::Director {

public:
    SwigDirector_CommonMain();
    virtual ~SwigDirector_CommonMain();
    virtual int OnElt(CommonElt const *pcElt) const;
    virtual unsigned int getCurrentPictureId() const;
    virtual unsigned int getCurrentSliceId() const;
    virtual unsigned int getCurrentLayerId() const;

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback3_t)();
    void swig_connect_director(SWIG_Callback0_t callbackOnElt, SWIG_Callback1_t callbackgetCurrentPictureId, SWIG_Callback2_t callbackgetCurrentSliceId, SWIG_Callback3_t callbackgetCurrentLayerId);

private:
    SWIG_Callback0_t swig_callbackOnElt;
    SWIG_Callback1_t swig_callbackgetCurrentPictureId;
    SWIG_Callback2_t swig_callbackgetCurrentSliceId;
    SWIG_Callback3_t swig_callbackgetCurrentLayerId;
    void swig_init_callbacks();
};

class SwigDirector_CommonMainH264 : public CommonMainH264, public Swig::Director {

public:
    SwigDirector_CommonMainH264();
    virtual ~SwigDirector_CommonMainH264();
    virtual int OnElt(CommonElt const *pcElt) const;
    virtual unsigned int getCurrentPictureId() const;
    virtual unsigned int getCurrentSliceId() const;
    virtual unsigned int getCurrentLayerId() const;

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback3_t)();
    void swig_connect_director(SWIG_Callback0_t callbackOnElt, SWIG_Callback1_t callbackgetCurrentPictureId, SWIG_Callback2_t callbackgetCurrentSliceId, SWIG_Callback3_t callbackgetCurrentLayerId);

private:
    SWIG_Callback0_t swig_callbackOnElt;
    SWIG_Callback1_t swig_callbackgetCurrentPictureId;
    SWIG_Callback2_t swig_callbackgetCurrentSliceId;
    SWIG_Callback3_t swig_callbackgetCurrentLayerId;
    void swig_init_callbacks();
};


#endif
