/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

using System;
using System.Runtime.InteropServices;

public class CommonMbVectorPtr : IDisposable, System.Collections.IEnumerable
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IList<CommonMb>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CommonMbVectorPtr(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CommonMbVectorPtr obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CommonMbVectorPtr() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          commonWRAPPINVOKE.delete_CommonMbVectorPtr(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public CommonMbVectorPtr(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (CommonMb element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public CommonMb this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array)
#else
  public void CopyTo(CommonMb[] array)
#endif
  {
    CopyTo(0, array, 0, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array, int arrayIndex)
#else
  public void CopyTo(CommonMb[] array, int arrayIndex)
#endif
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(int index, System.Array array, int arrayIndex, int count)
#else
  public void CopyTo(int index, CommonMb[] array, int arrayIndex, int count)
#endif
  {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

#if !SWIG_DOTNET_1
  System.Collections.Generic.IEnumerator<CommonMb> System.Collections.Generic.IEnumerable<CommonMb>.GetEnumerator() {
    return new CommonMbVectorPtrEnumerator(this);
  }
#endif

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new CommonMbVectorPtrEnumerator(this);
  }

  public CommonMbVectorPtrEnumerator GetEnumerator() {
    return new CommonMbVectorPtrEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class CommonMbVectorPtrEnumerator : System.Collections.IEnumerator
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerator<CommonMb>
#endif
  {
    private CommonMbVectorPtr collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public CommonMbVectorPtrEnumerator(CommonMbVectorPtr collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public CommonMb Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (CommonMb)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

#if !SWIG_DOTNET_1
    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
#endif
  }

  public void Clear() {
    commonWRAPPINVOKE.CommonMbVectorPtr_Clear(swigCPtr);
  }

  public void Add(CommonMb x) {
    commonWRAPPINVOKE.CommonMbVectorPtr_Add(swigCPtr, CommonMb.getCPtr(x));
  }

  private uint size() {
    uint ret = commonWRAPPINVOKE.CommonMbVectorPtr_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = commonWRAPPINVOKE.CommonMbVectorPtr_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    commonWRAPPINVOKE.CommonMbVectorPtr_reserve(swigCPtr, n);
  }

  public CommonMbVectorPtr() : this(commonWRAPPINVOKE.new_CommonMbVectorPtr__SWIG_0(), true) {
  }

  public CommonMbVectorPtr(CommonMbVectorPtr other) : this(commonWRAPPINVOKE.new_CommonMbVectorPtr__SWIG_1(CommonMbVectorPtr.getCPtr(other)), true) {
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public CommonMbVectorPtr(int capacity) : this(commonWRAPPINVOKE.new_CommonMbVectorPtr__SWIG_2(capacity), true) {
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  private CommonMb getitemcopy(int index) {
    IntPtr cPtr = commonWRAPPINVOKE.CommonMbVectorPtr_getitemcopy(swigCPtr, index);
    CommonMb ret = (cPtr == IntPtr.Zero) ? null : new CommonMb(cPtr, false);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private CommonMb getitem(int index) {
    IntPtr cPtr = commonWRAPPINVOKE.CommonMbVectorPtr_getitem(swigCPtr, index);
    CommonMb ret = (cPtr == IntPtr.Zero) ? null : new CommonMb(cPtr, false);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, CommonMb val) {
    commonWRAPPINVOKE.CommonMbVectorPtr_setitem(swigCPtr, index, CommonMb.getCPtr(val));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(CommonMbVectorPtr values) {
    commonWRAPPINVOKE.CommonMbVectorPtr_AddRange(swigCPtr, CommonMbVectorPtr.getCPtr(values));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public CommonMbVectorPtr GetRange(int index, int count) {
    IntPtr cPtr = commonWRAPPINVOKE.CommonMbVectorPtr_GetRange(swigCPtr, index, count);
    CommonMbVectorPtr ret = (cPtr == IntPtr.Zero) ? null : new CommonMbVectorPtr(cPtr, true);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, CommonMb x) {
    commonWRAPPINVOKE.CommonMbVectorPtr_Insert(swigCPtr, index, CommonMb.getCPtr(x));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, CommonMbVectorPtr values) {
    commonWRAPPINVOKE.CommonMbVectorPtr_InsertRange(swigCPtr, index, CommonMbVectorPtr.getCPtr(values));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    commonWRAPPINVOKE.CommonMbVectorPtr_RemoveAt(swigCPtr, index);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    commonWRAPPINVOKE.CommonMbVectorPtr_RemoveRange(swigCPtr, index, count);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public static CommonMbVectorPtr Repeat(CommonMb value, int count) {
    IntPtr cPtr = commonWRAPPINVOKE.CommonMbVectorPtr_Repeat(CommonMb.getCPtr(value), count);
    CommonMbVectorPtr ret = (cPtr == IntPtr.Zero) ? null : new CommonMbVectorPtr(cPtr, true);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    commonWRAPPINVOKE.CommonMbVectorPtr_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    commonWRAPPINVOKE.CommonMbVectorPtr_Reverse__SWIG_1(swigCPtr, index, count);
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, CommonMbVectorPtr values) {
    commonWRAPPINVOKE.CommonMbVectorPtr_SetRange(swigCPtr, index, CommonMbVectorPtr.getCPtr(values));
    if (commonWRAPPINVOKE.SWIGPendingException.Pending) throw commonWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(CommonMb value) {
    bool ret = commonWRAPPINVOKE.CommonMbVectorPtr_Contains(swigCPtr, CommonMb.getCPtr(value));
    return ret;
  }

  public int IndexOf(CommonMb value) {
    int ret = commonWRAPPINVOKE.CommonMbVectorPtr_IndexOf(swigCPtr, CommonMb.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(CommonMb value) {
    int ret = commonWRAPPINVOKE.CommonMbVectorPtr_LastIndexOf(swigCPtr, CommonMb.getCPtr(value));
    return ret;
  }

  public bool Remove(CommonMb value) {
    bool ret = commonWRAPPINVOKE.CommonMbVectorPtr_Remove(swigCPtr, CommonMb.getCPtr(value));
    return ret;
  }

}

}
