/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

public enum CommonElementType_t {
  CommonEltType_Header,
  CommonEltType_Function,
  CommonEltType_Syntax,
  CommonEltType_Control,
  CommonEltType_Error,
  CommonEltType_Mb,
  CommonEltType_Section,
  CommonEltType_Nalu
}

}
