/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

public enum IntraChromaPredMode {
  Intra_Chroma_DC,
  Intra_Chroma_Horizontal,
  Intra_Chroma_Vertical,
  Intra_Chroma_Plane
}

}
