/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

public enum Intra4x4PredMode {
  Intra_4x4_Vertical,
  Intra_4x4_Horizontal,
  Intra_4x4_DC,
  Intra_4x4_Diagonal_Down_Left,
  Intra_4x4_Diagonal_Down_Right,
  Intra_4x4_Vertical_Right,
  Intra_4x4_Horizontal_Down,
  Intra_4x4_Vertical_Left,
  Intra_4x4_Horizontal_Up
}

}
