/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

public enum MbMode {
  MODE_SKIP = 0,
  MODE_16x16 = 1,
  MODE_16x8 = 2,
  MODE_8x16 = 3,
  MODE_8x8 = 4,
  MODE_8x8ref0 = 5,
  INTRA_4X4 = 6,
  MODE_PCM = 25+6,
  INTRA_BL = 36,
  NOT_AVAILABLE = 99
}

}
