/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.thialgou.commonWRAP {

public enum NalUnitType {
  NAL_UNIT_UNSPECIFIED_0 = 0,
  NAL_UNIT_CODED_SLICE = 1,
  NAL_UNIT_CODED_SLICE_DATAPART_A = 2,
  NAL_UNIT_CODED_SLICE_DATAPART_B = 3,
  NAL_UNIT_CODED_SLICE_DATAPART_C = 4,
  NAL_UNIT_CODED_SLICE_IDR = 5,
  NAL_UNIT_SEI = 6,
  NAL_UNIT_SPS = 7,
  NAL_UNIT_PPS = 8,
  NAL_UNIT_ACCESS_UNIT_DELIMITER = 9,
  NAL_UNIT_END_OF_SEQUENCE = 10,
  NAL_UNIT_END_OF_STREAM = 11,
  NAL_UNIT_FILLER_DATA = 12,
  NAL_UNIT_SPS_EXTENSION = 13,
  NAL_UNIT_PREFIX = 14,
  NAL_UNIT_SUBSET_SPS = 15,
  NAL_UNIT_RESERVED_16 = 16,
  NAL_UNIT_RESERVED_17 = 17,
  NAL_UNIT_RESERVED_18 = 18,
  NAL_UNIT_AUX_CODED_SLICE = 19,
  NAL_UNIT_CODED_SLICE_SCALABLE = 20,
  NAL_UNIT_RESERVED_21 = 21,
  NAL_UNIT_RESERVED_22 = 22,
  NAL_UNIT_RESERVED_23 = 23
}

}
